<a href="https://colab.research.google.com/github/sak-shi-collab/8_SAKSHI_D2/blob/main/Lab1_and_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [5]:
data=pd.read_csv("/content/cafe.csv")

In [ ]:
data.info()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [6]:
data.head()

,Store ID,Name,Brand,Ownership Type,Address,City,State,Country,Postal Code,Latitude,Longitude,Launch Date,AFF-Mon,AFF-Tue,AFF-Wed,AFF-Thu,AFF-Fri,AFF-Sat,AFF-Sun
0,92040,Fort,Railey,JointV,"Elphinstone Building, Horniman Circle, Veer Na...",Mumbai,MH,IN,400001,18.932308,72.834091,12/8/2013 22:41,352,107,300,356,462,515,385
1,92351,Goregaon East - Oberoi Mall,Railey,JointV,"Off Western Express Highway, Goregaon (East)",Mumbai,MH,IN,400063,19.174065,72.860535,12/8/2013 22:41,392,184,358,378,509,580,389
2,92413,Colaba,Railey,JointV,"Hotel Taj Mahal Palace, Apollo Bunder, Apollo ...",Mumbai,MH,IN,400005,18.921476,72.832436,12/8/2013 22:41,264,134,367,437,456,585,422
3,113991,Powai,Railey,JointV,"Prudential Bldg Hiranandani Bus Park, Gr Fl, C...",Mumbai,MH,IN,400076,19.116285,72.909683,12/8/2013 22:41,356,132,345,443,506,556,373
4,114012,Indira Gandhi Itnl Arpt-T3Gate15,Railey,JointV,"International Departure, Near Gate 15, Terminal 3",New Delhi,DL,IN,110037,28.556322,77.102501,12/8/2013 22:41,321,104,362,435,485,528,413

Question no.1

In [7]:
import pandas as pd


df = pd.read_csv('housing_dataset.csv')


smallest_houses = df.nsmallest(5, 'median_house_value')


largest_houses = df.nlargest(5, 'median_house_value')

print("--- 5 Smallest House Values ---")
print(smallest_houses[['median_house_value', 'median_income', 'housing_median_age']])

print("\n--- 5 Largest House Values ---")
print(largest_houses[['median_house_value', 'median_income', 'housing_median_age']])

--- 5 Smallest House Values ---
       median_house_value  median_income  housing_median_age
2521                14999         1.6607                  16
2799                14999         2.1000                  19
9188                14999         4.1932                  52
19802               14999         0.5360                  36
5887                17500         2.3667                  39

--- 5 Largest House Values ---
     median_house_value  median_income  housing_median_age
89               500001         1.2434                  52
459              500001         1.1696                  52
493              500001         7.8521                  52
494              500001         9.3959                  52
509              500001         7.8772                  52


`

Question no.2

In [11]:

subset_df = df.loc[:, ['median_income', 'median_house_value']]


print(subset_df.head())

   median_income  median_house_value
0         8.3252              452600
1         8.3014              358500
2         7.2574              352100
3         5.6431              341300
4         3.8462              342200

Question no.3

In [12]:

df = pd.read_csv('housing_dataset.csv')

subset_iloc = df.iloc[0:4, 0:6]
print(subset_iloc)

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0
1    -122.22     37.86                  21         7099          1106.0
2    -122.24     37.85                  52         1467           190.0
3    -122.25     37.85                  52         1274           235.0

   population
0         322
1        2401
2         496
3         558

Question no.4

In [10]:

df = pd.read_csv('housing_dataset.csv')

grouped_df = df.groupby(['housing_median_age', 'median_house_value'])[['total_rooms']].mean().reset_index()

print(grouped_df.head())

   housing_median_age  median_house_value  total_rooms
0                   1               55000          6.0
1                   1              141700         83.0
2                   1              189200       2254.0
3                   1              191300       2062.0
4                   2               47500         96.0

  Question no.5

In [15]:
df.sort_values(by ='median_house_value')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
19802,-123.17,40.31,36,98,28.0,18,8,0.5360,INLAND,14999
2521,-122.74,39.71,16,255,73.0,85,38,1.6607,INLAND,14999
2799,-117.02,36.40,19,619,239.0,490,164,2.1000,INLAND,14999
9188,-117.86,34.24,52,803,267.0,628,225,4.1932,INLAND,14999
5887,-118.33,34.15,39,493,168.0,259,138,2.3667,<1H OCEAN,17500
...,...,...,...,...,...,...,...,...,...,...
18321,-122.13,37.45,37,1287,197.0,510,206,7.9029,NEAR BAY,500001
18354,-122.11,37.36,34,1575,183.0,511,180,13.1867,NEAR BAY,500001
18355,-122.13,37.37,30,2139,260.0,742,242,11.8060,NEAR BAY,500001
18356,-122.14,37.38,26,2859,343.0,951,336,10.4277,NEAR BAY,500001
18357,-122.10,37.36,32,1433,199.0,498,201,9.3586,NEAR BAY,500001

Question no.6

In [17]:

df = pd.read_csv('housing_dataset.csv')
df = df.drop(columns=['ocean_proximity'])

print(df.columns.tolist())

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']

Question no.7

In [16]:

result = df[(df['median_house_value'] >= 40000) & (df['median_house_value'] <= 100000)].head(5)

print(result)

    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
23    -122.27     37.84                  52         1688           337.0
26    -122.28     37.85                  49         1130           244.0
35    -122.27     37.83                  49         1215           282.0
51    -122.27     37.82                  43         1868           456.0
52    -122.27     37.82                  41         3221           853.0

    population  households  median_income ocean_proximity  median_house_value
23         853         325         2.1806        NEAR BAY               99700
26         607         239         2.4597        NEAR BAY               93800
35         570         264         1.4861        NEAR BAY               97200
51        1061         407         1.5045        NEAR BAY               93800
52        1959         720         1.1108        NEAR BAY               97500

add last column to first

slicing back to dataframe(python library)

In [19]:
cols = [df.columns[-1]] + list(df.columns[:-1])
df = df[cols]

pop and push

In [20]:
last_col = df.pop(df.columns[-1])
df.insert(0, last_col.name, last_col)



> reorder by iloc using the indexing staritng from 0 as last column

In [21]:
df = df.iloc[:, [-1] + list(range(len(df.columns) - 1))]

reorder by loc

In [ ]:
df = df.loc[:, [df.columns[-1]] + df.columns[:-1].tolist()]